# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python mnist_train.py > result.txt
    - name: Send results as comment
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.CML_TOKEN }}
        script: |
          const octokit = context.github;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const issue_number = context.issue.number;
          const message = `
          **Test Results**

          Accuracy: ${result}
          `;

          await octokit.issues.createComment({
            owner,
            repo,
            issue_number,
            body: message
          });
