# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python mnist_train.py > result.txt
    - name: Send results as comment
      uses: actions/github-script@v4
      with:
          script: |
            const githubToken = process.env.GITHUB_TOKEN;
            const fs = require('fs');
            const result = fs.readFileSync('result.txt', 'utf8').trim();

            const message = `
            **Test Results**

            Accuracy: ${result}
            `;

            const octokit = new github.GitHub(githubToken);
            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
        
